#!/usr/bin/env php
<?php

// Load phillip dependencies
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

// Load project dependencies
if (file_exists('vendor/autoload.php')) {
    require 'vendor/autoload.php';
}

$runner = Phillip\Runner::instance();
$runner->run();
